fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        course:
            index_name: "course"  # Name of the Elasticsearch index
            properties:
                id:
                    type: integer
                videoPathName:
                    type: text
                cover:
                    type: text
                url:
                    type: text
                label:
                    type: text
                description:
                    type: text
                category:
                    type: object
                    properties:
                        id:
                            type: integer
                        label:
                            type: text
                sections:
                    type: nested
                    properties:
                        id:
                            type: integer
                        title:
                            type: text
                        description:
                            type: text
                medias:
                    type: nested
                    properties:
                        fileName:
                            type: text
            persistence:
                driver: orm
                model: App\Entity\Course
                listener: false
            