security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            id:  App\Security\PasswordHasher\PasswordHasher

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        custom_ldap_server:
            id: custom_ldap_provider
        # this provider will be kept in case we need to rollback
        ldap_server:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: '%env(LDAP_BASE_DN)%' # Domaine dans le LDAP
                search_dn: '%env(LDAP_SEARCH_DN)%' # Utilisateur dans l'AD (readonly)
                search_password: '%env(LDAP_SEARCH_PASSWORD)%' # Mot de passe de l'utilisateur dans l'AD (readonly)
                uid_key: uid
                default_roles: ROLE_USER
                password_attribute: userPassword
                extra_fields: [ 'employeeType', 'userPassword'  ]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
        main:
            lazy: true
#            provider: ldap_server
            provider: custom_ldap_server
            custom_authenticator: App\Security\CustomLdapAuthenticator
            logout:
                path: app_logout

    role_hierarchy:
        ROLE_CRCI_MANAGER: ROLE_USER,
        ROLE_NETWORK_HOLDER: ROLE_USER
        ROLE_MANAGER: ROLE_USER
        ROLE_ADMIN: [ROLE_CRCI_MANAGER, ROLE_NETWORK_HOLDER, ROLE_MANAGER]

    access_control:
          - { path: ^/login$, roles: PUBLIC_ACCESS }
          - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:

            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
