security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'plaintext'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        ldap_server:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: '%env(LDAP_BASE_DN)%' # Domaine dans le LDAP
                search_dn: '%env(LDAP_SEARCH_DN)%' # Utilisateur dans l'AD (readonly)
                search_password: '%env(LDAP_SEARCH_PASSWORD)%' # Mot de passe de l'utilisateur dans l'AD (readonly)
                uid_key: uid
                default_roles: ROLE_USER
                password_attribute: userPassword
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
        main:
            lazy: true
            provider: ldap_server
            custom_authenticator: App\Security\CustomLdapAuthenticator
            logout:
                path: app_logout
                #
    access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:

            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
